export default {

    HOME:"Home",
    USER_BOOKING:"UserBooking",
    USER_PROFILE:"UserProfile",
    CART:'Cart',
    USER_WISHLIST:"UserWishList",

    ARTIST_HOME:"ARTIST_HOME",
    ARTIST_BOOKING:"ARTIST_BOOKING",
    ARTIST_PROFILE:"ARTIST_PROFILE",

    ARTIST_CHAT:"ARTIST_CHAT",

    USER_CHAT:"USER_CHAT",

    TRACK_ARTIST:"TRACK_ARTIST",

    ARTIST_SAVED_ADDR:"ARTIST_SAVED_ADDR",

    MY_GALLERY:"MY_GALLERY",

    BOOK_VIRTUAL_TRAINIG:"BOOK_VIRTUAL_TRAINIG"
    
}