# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
# Flipper is disabled due to compatibility issues with Xcode 26 / iOS 26 SDK
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'flawless' do
  config = use_native_modules!

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  
  # Facebook SDK
  pod 'FBSDKCoreKit', '~> 17.0'
  pod 'FBSDKLoginKit', '~> 17.0'

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'flawlessTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Fix for Xcode 26 linker crash - disable deprecated ld_classic flag
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        # Remove -ld_classic from OTHER_LDFLAGS if present
        ldflags = build_config.build_settings['OTHER_LDFLAGS']
        if ldflags.is_a?(Array)
          build_config.build_settings['OTHER_LDFLAGS'] = ldflags.reject { |flag| flag == '-ld_classic' || flag == 'ld_classic' }
        elsif ldflags.is_a?(String)
          build_config.build_settings['OTHER_LDFLAGS'] = ldflags.gsub(/-?ld_classic/, '').gsub(/\s+/, ' ').strip
        end
      end
    end
    
    # Also fix the main project (not just Pods)
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |build_config|
          ldflags = build_config.build_settings['OTHER_LDFLAGS']
          if ldflags.is_a?(Array)
            build_config.build_settings['OTHER_LDFLAGS'] = ldflags.reject { |flag| flag == '-ld_classic' || flag == 'ld_classic' }
          elsif ldflags.is_a?(String)
            build_config.build_settings['OTHER_LDFLAGS'] = ldflags.gsub(/-?ld_classic/, '').gsub(/\s+/, ' ').strip
          end
        end
      end
    end
  end
end
